print("There are some malware in such directory:",end="")
print(" ","home","tek","python",sep="/",end=";")
print(" ","etc","shadow","password",sep="/",end=";")
print(" ","home","tek","java",sep="/",end=";")
print(" ",sep="",end="...")
